.gitignore, package.json, scripts/fetch-schema.js, scripts/fsPromise.js, scripts/githubApi.js, scripts/update-schema.js, src/app/component/partial/ClearSilencedEntriesDialog/Dialog.js, src/app/component/partial/SilencesList/SilencesListItem.js, src/schema/combined.graphql, yarn.lock
Closes #50
Add new `fetch-schema` script to fix the reference to the server GraphQL schema which broke as a result of the repo split. 
Fixes compatibility with the schema changes from https://github.com/sensu/sensu-go/pull/2843
=> Fix update-schema build script

src/lib/component/partial/ToolbarSelect/Option.js
Unfortunately `eslint-plugin-import` doesn't catch broken references in restructured module imports.
This issue is something that can be avoided entirely by using flow or typescript 😉
=> Fix broken imports in ToolbarSelect/Option component

src/lib/component/partial/CheckDetailsContainer/CheckDetailsContainer.js, src/lib/component/partial/CheckDetailsContainer/CheckDetailsToolbar.js, src/lib/component/partial/ChecksList/ChecksListHeader.js, src/lib/component/partial/ChecksList/ChecksListItem.js, src/lib/component/partial/ChecksList/ChecksListToolbar.js, src/lib/component/partial/EntitiesList/EntitiesListHeader.js, src/lib/component/partial/EntitiesList/EntitiesListItem.js, src/lib/component/partial/EntitiesList/EntitiesListToolbar.js, src/lib/component/partial/EntityDetailsContainer/EntityDetailsContainer.js, src/lib/component/partial/EntityDetailsContainer/EntityDetailsToolbar.js, src/lib/component/partial/EventDetailsContainer/EventDetailsContent.js, src/lib/component/partial/EventDetailsContainer/EventDetailsToolbar.js, src/lib/component/partial/EventsList/EventsListHeader.js, src/lib/component/partial/EventsList/EventsListItem.js, src/lib/component/partial/EventsList/EventsListToolbar.js, src/lib/component/partial/QuickNav/Nav.js, src/lib/component/partial/SilencesList/SilencesListHeader.js, src/lib/component/partial/SilencesList/SilencesListItem.js, src/lib/component/partial/SilencesList/SilencesListToolbar.js, src/lib/component/partial/ToolbarMenu/Item.js, src/lib/component/partial/ToolbarMenu/ToolbarMenu.js, src/lib/component/partial/ToolbarMenu/index.js, src/lib/component/view/CheckDetailsView.js, src/lib/component/view/ChecksView.js, src/lib/component/view/EntitiesView.js, src/lib/component/view/EntityDetailsView.js, src/lib/component/view/EventDetailsView.js, src/lib/component/view/EventsView.js, src/lib/component/view/SilencesView.js
Closes #48
The `toolbarItems` prop, with the signature `({items: React.ReactElement<ToolbarMenu.Item>[], collapsed?: boolean, width?: number }) => React.ReactElement<ToolbarMenu.Item>[]`, allows the consumer of any of the main view components to inject additional toolbar menu items when the view is rendered.
Example customization:
```jsx
import {ChecksView as BaseChecksView} from '/lib/component/view';
export default class ChecksView {
state = {
modalOpen: false,
};
render() {
return (
<React.Fragment>
<ChecksView
{...this.props}
toolbarItems={({items}) => [
...items,
<ToolbarMenu.Item key="example">
<button
onClick={() =>
this.setState({modalOpen: true})
}
>
...
</button>
</ToolbarMenu.Item>,
]}
/>
{this.state.modalOpen && <ExampleModal/>}
</React.Fragment>
);
}
}
```
=> Add toolbarItems callback prop to view components

package.json, src/app/index.js, yarn.lock
Tap event plugin is deprecated and no longer supported.
see: https://github.com/zilverline/react-tap-event-plugin#deprecated
=> Remove deprecated react-tap-event-plugin

src/lib/component/partial/ListHeader/ListHeader.js
Prevent the `ListHeader` component select-all checkbox from appearing as checked when the list is empty.
Before:
After:
=> Show correct checkbox state for empty list

src/lib/component/base/Banner.js
Fixes a bug causing the app to crash with `cannot read property 600 of undefined` error when attempting to render a banner (regression caused by #9)
=> Fix regression in banner component

src/lib/component/view/CheckDetailsView.js, src/lib/component/view/EntityDetailsView.js, src/lib/component/view/EventDetailsView.js
Avoids the following error by ensuring the ID is present for the cache to reference.
> "Invariant Violation: Store error" the application attempted to write an object
> with no provided id but the store already contains an id of
> srn:entities:sensu-devel:... this object. The selectionSet that was
> trying to be written ...
* [Apollo Source](https://github.com/apollographql/apollo-client/blob/26c4ff31c6e0853fe93094ca83e502fa0eef580c/packages/apollo-cache-inmemory/src/writeToStore.ts#L359-L371)
* [Related Feature Request](https://github.com/apollographql/apollo-feature-requests/issues/23)
=> Include id field when checks, entities and events

src/lib/component/base/Banner.js
The alert banner was importing some icons incorrectly, causing them to not display. It was also causing some console errors which took some scrolling to get past.
Before:
After:
=> [Web] Touch up banner issues

.github/issue_template.md, .github/pull_request_template.md
Adds a PR and an issue template. This also (apparently) auto-assigns the web-ui label to all issues and PRs, making it easier to filter the web ui issues in zenhub. 
Followed the example from sensu-enterprise-go repo.
=> Add PR and issue templates

src/lib/component/base/Toast.js, src/lib/component/partial/CheckDetailsContainer/CheckDetailsExecuteAction.js, src/lib/component/partial/CheckDetailsContainer/CheckDetailsPublishAction.js, src/lib/component/partial/CheckDetailsContainer/CheckDetailsUnpublishAction.js, src/lib/component/partial/ChecksList/ChecksList.js, src/lib/component/partial/EventDetailsContainer/EventDetailsReRunAction.js, src/lib/component/partial/EventsList/EventsList.js, src/lib/component/relocation/index.js, src/lib/component/relocation/useBanner.js, src/lib/component/relocation/usePromiseBoundComponent.js, src/lib/component/relocation/useToast.js, src/lib/component/toast/ExecuteCheckStatusToast.js, src/lib/component/toast/PublishCheckStatusToast.js, src/lib/component/toast/index.js, src/lib/error/index.js
Handle check execute and publish/unpublish errors by displaying error toasts leveraging newly created utilities for implementing status toasts for async actions.
Errors network/api errors encountered during graphql mutations should not result in an app crash state but should still alert the user. 
Yes, but as a summary of changes from this and further PRs which add additional error handling.
No.
There are some large diffs in component files that were migrated from a class implementation to functional components. This was a necessary change to be able to use React hooks (which underpin the new toast-creation utilities) in these locations. There are no other intended changes to look out for.
No.
Manual testing of the affected views.
=> Display errors in status toasts

src/lib/component/root/ErrorRoot.js, src/lib/exceptionHandler/index.js, src/lib/util/error.js
Patch a flaw in the global error handling logic to ensure that values that are not `Error` class instances are displayed.
Closes #104
No.
No.
No.
No.
Manual in-browser testing.
=> Prevent non Error instances from breaking the error handler

src/lib/mutation/createSilence.js
This change implements a looser test to check if the error represents a resource-already-exists error.
At some point in the past, the GraphQL resolver changed its error formatting behavior; `code = 3 desc = resource already exists` became `resource already exists` in the response.
We need such a check because the createSilence mutation represents a special error-handling case.
see: https://github.com/sensu/sensu-go/issues/2964
=> Fix broken createSilence mutation error handling logic

src/app/index.js, src/lib/component/icon/index.js, src/lib/component/partial/HandlersList/HandlersList.js, src/lib/component/partial/HandlersList/HandlersListHeader.js, src/lib/component/partial/HandlersList/HandlersListItem.js, src/lib/component/partial/HandlersList/HandlersListItemDetails.js, src/lib/component/partial/HandlersList/HandlersListToolbar.js, src/lib/component/partial/HandlersList/index.js, src/lib/component/partial/index.js, src/lib/component/view/HandlersView.js, src/lib/component/view/index.js
⚠️ This change requires https://github.com/sensu/sensu-go/pull/2951
This change allows users to navigate to `/:namespace/handlers` route to view a collection of Handlers fetched from GraphQL. This PR address part of sensu/web#89, the rest of this issue will be address in a separate PR. 
From the Handlers collection view users can:
1. Sort Handlers by `name` using a select dropdown.
2. Filter Handlers by `type` (`pipe`, `set`, `tcp`, or `udp`) using a select dropdown.
Handlers shown in the collection are displayed with contextual details determined by the 'type' of handler in the list (`pipe`, `set`, `tcp`,`udp`). Each type displays details that are relevant to the handler type. For example, `pipe` handlers display the command property and `tcp` handlers display socket information (port, …
=> Allow users to view a collection of Handlers

src/app/index.js, src/lib/component/partial/HandlerDetailsContainer/HandlerDetailsConfiguration.js, src/lib/component/partial/HandlerDetailsContainer/HandlerDetailsContainer.js, src/lib/component/partial/HandlerDetailsContainer/HandlerDetailsToolbar.js, src/lib/component/partial/HandlerDetailsContainer/index.js, src/lib/component/partial/LabelsAnnotationsCell/LabelsAnnotationsCell.js, src/lib/component/partial/index.js, src/lib/component/view/HandlerDetailsView.js, src/lib/component/view/index.js
This change allows users to navigate to /:namespace/handlers/:handler_name` route to view the configuration of an individual Handler fetched from GraphQL. This PR address part of #89, the rest of this issue is addressed in #108.
From the Handler details view users can see the following attributes:
- Name
- Type
- Filters (as a list)
- Socket (the following format: `{scheme}://{host}:{port}`)
- Timeout
- Handers (as a click-able list)
- Command
- ENV vars
- Labels
- Annotations
**Example Handler (pipe handler):**
This change addresses #89 
> As a Sensu user, I would like the ability to view a list of my handlers and see the details of a particular one that I select.
Nope.
Nope,
Nope. 
Manually. Build and run the branch locally, create some handlers, then navigate to …
=> Allow users to view the configuration of an individual Handler

src/lib/component/view/HandlerDetailsView.js
Avoids the following error by ensuring the ID is present for the cache to reference.
> "Invariant Violation: Store error" the application attempted to write an object
> with no provided id but the store already contains an id of
> srn:handlers:sensu-devel:... this object. The selectionSet that was
> trying to be written ...
>
> apollographql/apollo-feature-requests#23
This changes supports sensu/sensu-enterprise-go/444 ([link](https://github.com/sensu/sensu-enterprise-go/issues/444))
As a user, I can delete a handler through the web UI.
Nope. 
Manually.
=> Include `id` field when querying handlers

src/lib/apollo/resolvers/deleted.graphql, src/lib/apollo/stateLink.js, src/lib/component/partial/HandlerDetailsContainer/HandlerDetailsConfiguration.js, src/lib/component/partial/HandlerDetailsContainer/HandlerDetailsContainer.js, src/lib/component/partial/HandlersList/HandlersList.js, src/lib/component/view/HandlerDetailsView.js
In order to track whether a record in the Apollo cache has been deleted, we set a client side field on the resource called `deleted`. This change updates the Handler related components and queries to include the `deleted` attribute.
This changes supports sensu/sensu-enterprise-go/444 (link)
> As a user, I can delete a handler through the web UI.
Nope.
Manually
=> Add client side `delete` field to Handler type

src/lib/component/partial/HandlerDetailsContainer/HandlerDetailsConfiguration.js
Previously, if a handler's timeout value was greater than 0, the UI would display the timeout as 1 second regardless of the actual value. Is was because we passed `true` to the `Maybe` component's render function when we should actually be using the `handler.timeout` integer value.
The UI previously displayed the wrong value for Handler Timeouts
No, this view did not previously exist before the current release. 
Manually.
=> [Bugfix] Properly display handler timeout

src/lib/component/base/CodeBlock/CodeBlock.js
This change updates the CodeBlock styles to use `overflow-x: auto` instead of `overflow-x: scroll` in order to hide unnecessary scroll bars from our CodeBlock elements.
Closes https://github.com/sensu/sensu-enterprise-go/issues/297
Nope.
Manually. 
1. Use a mouse.
2. Create a check with a short command. (eg. echo 'hi')
3. Logon to web.
4. Navigate to the check that you created in step two.
5. Observe the scrollbar.
=> Hide scroll bars from CodeBlock elements

src/lib/component/partial/CronDescriptor/CronDescriptor.js, src/lib/util/cron.js, src/lib/util/cron.test.js, src/lib/util/date.js, src/lib/util/date.test.js, src/lib/util/index.js
Add support for formatting non-standard cron expressions (ex. `@hourly`, `@every 10m` etc.).
Prevent the `CronDescriptor` component from raising an error in the event that a invalid cron expression can not be formatted.
Closes #114
Yes. Still TODO
No
Parsing `@every <duration>` expressions correctly according to the sensu-go backend (see: https://godoc.org/github.com/robfig/cron#hdr-Predefined_schedules) requires a go `time.parseDuration` compatible implementation in js. A truly compatible implementation isn't possible without a 64 bit int type, so the `parseDuration` function added in this PR implements identical parsing behavior but succumb to floating-point error in _exteme_ cases. For our needs this is a fine compromise as we don't need need large-value nanosecond precision that …
=> Support non-standard and invalid cron expressions

package.json, src/vendor/@material-ui-chip-input.js, yarn.lock
This change adds [`material-ui-chip-input`](https://github.com/TeamWertarbyte/material-ui-chip-input#readme) as a dependency for the web application to support filtering enhancements in the enterprise version of the application.
Supports sensu/sensu-enterprise-go#470 by adding a library that handles chip input and chip rendering.
No.
Manually, by importing the vendor'd version of the library and attempting to render it in a component. 
```
import ChipInput from "/vendor/@material-ui-chip-input";
```
=> Add `material-ui-chip-input` as a dependency

src/lib/apollo/resolvers/lastNamespace.graphql, src/lib/apollo/resolvers/lastNamespace.js
Avoid blindly redirecting our users to 'default' namespace, when `lastNamespace` is not unset.
Closes #30 
Yup.
No.
No.
None required.
Manual.
=> Avoid blindly sending user to 'default' namespace

scripts/upload-artifacts.js
Updates the `upload-artifacts` scripts configurable with a [filepath] and [prefix] so that the script can be reused by the enterprise project.
Related to sensu/sensu-enterprise-go#477
=> Make upload-artifacts script configurable

src/lib/component/util/QueryParams/index.tsx, src/lib/component/util/index.tsx
Babel does not allow re-exporting imported TypeScript types since it forces the `isolatedModules` flag. The workaround is to use wildcard exports which allows TypeScript to resolve the types but prevents babel from trying to do so.
see: https://babeljs.io/docs/en/babel-plugin-transform-typescript
see: https://github.com/Microsoft/TypeScript/issues/21194
Fixes this problem:
No.
No.
Replacing named exports with wildcard exports more-or-less widens the shared namespace. Care must be taken to ensure that all exports from a file targeted with `export * from` have non-conflicting names.
No.
Manually tested the vendored package.
=> Replace named type exports with wildcard export

package.json
This change bumps the GraphQL Schema Ref to `92fa1ee` to include the latest schema changes from https://github.com/sensu/sensu-go/pull/3049
This change supports a [bug fix Sensu Enterprise](https://github.com/sensu/sensu-enterprise-go/issues/496)
Manually, by inspecting the schema files generated by running `yarn` locally.
=> Bump GraphQL Schema Ref to 92fa1ee

package.json, src/lib/apollo/client.tsx, src/lib/apollo/httpLink.tsx, src/lib/apollo/introspectionLink.js, src/lib/apollo/tokenRefreshLink.js, src/vendor/apollo-link-context.tsx, src/vendor/index.tsx, yarn.lock
https://github.com/sensu/web/pull/144 removes the `apollo-link-context` dependency from our Apollo Client implementation, but it breaks our Apollo Link contract in Sensu Enterprise.
The goal of this ticket is to re-implement `apollo-link-context`, so that our Apollo Links can retrieve the client from context.
Right now, if we attempt to vendor in the latest changes from sensu/web, the Enterprise Web app crashes.
Supports https://github.com/sensu/sensu-enterprise-go/issues/523
Manually.
=> Re-add 'apollo-link-context' dependency 

src/lib/util/filterParams.tsx
This change updates the `parseFilter` implementation in `lib/util/filterParams.tsx` to allow filter values to include ":" values. The previous implementation used `String.split()` which discards the other split values in the string. 
This implementation looks for the first ":" separator, and splits the key and value, retaining the rest of the value even if it includes ":".
Closes https://github.com/sensu/sensu-enterprise-go/issues/529
Manual
=> Update `parseFilter` logic to allow for ":" values

package.json, src/app/index.js, src/lib/component/icon/index.js, src/lib/component/partial/EventFiltersList/EventFiltersList.tsx, src/lib/component/partial/EventFiltersList/EventFiltersListHeader.tsx, src/lib/component/partial/EventFiltersList/EventFiltersListItem.tsx, src/lib/component/partial/EventFiltersList/EventFiltersListToolbar.tsx, src/lib/component/partial/EventFiltersList/index.tsx, src/lib/component/partial/index.js, src/lib/component/view/EventFiltersView.tsx, src/lib/component/view/index.js, src/lib/util/filterParams.tsx
This change creates a List View for the `Event Filter` resource type. 
Closes https://github.com/sensu/sensu-enterprise-go/issues/507
> The goal of this issue is to create List View for the Filters similar to that of our other resources (Checks, Handlers, Entities, etc.).
>
> *Requirements*
>
> - Create a new route for `/:namespace/filters`
> - Fetch a paginated list of Filter resources from the namespace.filters GraphQL field
> - Display a paginated list of Filter resources
> - A navigation link should be added in the sidebar and menu to navigate to this view.
> - Each line item in the list should include the Filter name and the Filter action
> - The list should be sortable by name (`asc`/`desc`) and action (`allow`/`deny`)
Manually. 
To manually verify this change you can run the …
=> Create a list view for the 'Event Filters' resource type.

src/app/index.js, src/lib/apollo/resolvers/deleted.graphql, src/lib/apollo/stateLink.js, src/lib/component/base/CodeHighlight/CodeHighlight.js, src/lib/component/base/CodeHighlight/CodeHighlight.worker.js, src/lib/component/partial/EntitiesList/EntitiesListHeader.js, src/lib/component/partial/EventFilterActionLabel/EventFilterActionLabel.tsx, src/lib/component/partial/EventFilterActionLabel/index.tsx, src/lib/component/partial/EventFilterDetailsContainer/EventFilterDetailsConfiguration.tsx, src/lib/component/partial/EventFilterDetailsContainer/EventFilterDetailsContainer.tsx, src/lib/component/partial/EventFilterDetailsContainer/EventFilterDetailsToolbar.tsx, src/lib/component/partial/EventFilterDetailsContainer/index.tsx, src/lib/component/partial/EventFiltersList/EventFiltersListHeader.tsx, src/lib/component/partial/EventFiltersList/EventFiltersListItem.tsx, src/lib/component/partial/ListHeader/ListHeader.js, src/lib/component/partial/index.js, src/lib/component/view/EventFilterDetailsView.tsx, src/lib/component/view/EventFiltersView.tsx, src/lib/component/view/index.js
This change adds the `/:namespace/filters/:filter` route to the application so that users can view the configuration of an Event Filter resource. 
Closes https://github.com/sensu/sensu-enterprise-go/issues/514
>The goal of this ticket is to create a `FiltersDetailsView` that allows users to view the configuration of a Filter resource.
> 
> **Requirements**
>  - Create a route at `/:namespace/filters/:filterName`
>  - Using the GraphQL `filters` field on the top level `Query` object, fetch a Filter given a `namespace` and a `filterName`. 
>  - Render the configuration of the Filter in the details view. (Filter Name, Namespace, Action, Assets, Filter Expressions, Labels, and Annotations)
Manually. 
To manually verify this change you can run the `sensu-backend` and the web application …
=> Create the Event Filter Details view

package.json, src/lib/component/partial/EventFilterDetailsContainer/EventFilterDetailsConfiguration.tsx, src/lib/component/partial/RuntimeAssetsCell/RuntimeAssetsCell.tsx, src/lib/component/partial/RuntimeAssetsCell/index.tsx, src/lib/component/partial/index.js
This change creates the `RuntimeAssetsCell` component and implements it in the `EventFilterDetailsConfiguration` component to render a list runtime assets. Previously, we had a UI element for runtime assets, but the `runtimeAssets` key wasn't added to the EventFilters query, so nothing would render.
Manually.
=> Add Runtime Assets to the Event FilterDetails view

src/lib/component/partial/EventDetailsContainer/EventDetailsReRunAction.js, src/lib/component/partial/EventDetailsContainer/EventDetailsToolbar.js
This change disables the "re-run" button for Proxy Entity Checks and for "keepalive" checks.
Previously, the Web UI allowed users to attempt to re-run a check against a proxy entity, but it wouldn't do anything because our application sends an empty array of subscriptions to the `executeCheck` mutation when the entity is a proxy entity.
The reason we don't preform check re-runs against proxy entities because to do so we would need to re-run the check against all its subscriptions. We believe that, as a user, clicking re-run on a check and having the check run against all subscriptions is not expected behaviour, and could lead to unwanted results.
In the future, we may implement a dialogue that would allow the user to select which subscriptions a check is run against, so that users have …
=> [Bug] Disable re-run action for proxy entity checks

yarn.lock
While the vulnerabilities should not be relevant to the product, update dependencies to appease audit.
=> Bump mixin-deep & set-value dependencies

src/lib/component/partial/Drawer.js, src/lib/component/partial/NamespaceLabel/NamespaceLabelBase.js, src/lib/component/partial/NamespaceSelector/NamespaceSelectorBuilder.js
Closes #162 
Changes the namespace selector in the drawer to show namespace in one line, just like the topbar.
It was requested.
=> Namespaces with hyphen are inline in drawer

src/lib/component/partial/ToolbarSelect/Button.js, src/vendor/react-router-dom.tsx
This change fixes a few erroneous imports in the repo that cause our Cypress testing framework to error on when developing in our https://github.com/sensu/sensu-enterprise-go repo.
This change supports exploration we are doing into the Cypress testing framework for end-to-end test
No.
Manually, by building and running the application without issue.
=> Fix imports to appease Cypress Testing Framework

src/lib/component/util/AuthInvalidRoute.js, src/lib/component/util/useQuery.tsx
If rejected discards the error from the promise returned by QueryObservable's `setOptions` method. Said error is already handled by the query subscription and there is no need to handle it twice.
Closes #169
=> Handle rejected result; fix refresh token crash

scripts/serve.js, src/app/index.js, src/lib/component/partial/AppBar.js, src/lib/component/partial/AppLayout.js, src/lib/component/partial/Drawer.js, src/lib/component/partial/NamespaceIcon/Connected.js, src/lib/component/partial/NamespaceSelector/NamespaceSelector.js, src/lib/component/partial/NamespaceSelector/NamespaceSelectorMenu.js, src/lib/component/util/NamespacesProvider/NamespacesProvider.js, src/lib/component/util/NamespacesProvider/WithNamespaces.js, src/lib/component/util/NamespacesProvider/context.js, src/lib/component/util/NamespacesProvider/index.js, src/lib/component/util/SyncNamespaces.js, src/lib/component/util/index.tsx, src/lib/util/NamespacesContext.js, src/lib/util/namespaceAPI.js
Switches to contacting the api for the namespaces endpoint, rather than using graphql. Makes contact more modular. 
https://github.com/sensu/sensu-enterprise-go/issues/609
Not particularly 
There were some, particularly with namespace icons. That system will likely have to be reworked. However, I also imagine when we will need to rework this soon either way.
No documentation required. It appears to function the same.
Manual testing.
=> Use namespaces endpoint

src/lib/component/root/ErrorRoot.js
Adds a button that additionally clears localStorage when the user encounters an unexpected exception.
If the issue is related to some data in localStorage, the user could find themselves stuck until they manually clear localStorage- assuming they even know how. Giving the user the option to clear the state should help in these unfortunate cases.
Closes #173 
Closes #175
Manual.
=> Add option to clear state when error dialog is encountered

src/lib/component/base/AppLayout/AppLayout.js, src/lib/component/partial/Drawer/FullDrawer.js
Signed-off-by: Melissa Page <73hl10n@gmail.com>
With the addition of #204 I introduced a bug where the nav bar was not scrolling properly on mobile. This fixes that.
The nav bar was underneath the table bar when scrolling. Now they're both sticky.
=> Fix issue with top bar scrolling on mobile

src/lib/apollo/tokenRefreshLink.js
With changes to access token expiry, the previous value meant that the token was _always_ refreshed before a query.
=> Reduce expiry threshold to one minute

src/lib/component/icon/index.tsx, src/lib/component/partial/Label/Label.js
Closes https://github.com/sensu/sensu-go/issues/3212 
Adds links to labels, and prettifies them
Uchiwa pairity
=> Add links to labels

package.json, src/lib/util/check.ts, src/vendor/jsbi.d.ts, src/vendor/jsbi.js, yarn.lock
Embed JSBI library to avoid crashes on Firefox. Minified copy of the library appears to lead to consistent crashes.
Closes sensu/sensu-enterprise-go#818
=> [Fix] Embed JSBI library to avoid crash on Firefox

src/lib/component/partial/EventsList/EventsListHeader.js
Ensure sorting the event list view does not lose selected filters.
Closes #244 
Manual
=> Ensure sorting a list view does not lose selected filters

src/lib/component/base/AvatarIcon/AvatarIcon.stories.js, src/lib/component/base/AvatarIcon/AvatarIcon.tsx, src/lib/component/base/AvatarIcon/index.tsx, src/lib/component/partial/SilencesList/SilencesListItem.js, src/lib/component/partial/UserAvatar/UserAvatar.stories.js, src/lib/component/partial/UserAvatar/UserAvatar.tsx, src/lib/component/partial/UserAvatar/index.js, src/lib/component/partial/index.js
Part of #248 
Allows a user to be associated with an avatar. Hashed from their username. 
Adds some cute flair and feeling to the app. Proper placeholder if we allow users to select their own icons.
=> Generated User Icons

src/lib/component/base/Drawer/Drawer.tsx
Use the layout's topBarHeight to set  the top position of the drawer.
Previously, contents of the drawer could be pushed outside of the container when a banner appeared.
Manual.
=> use topBarHeight to set Drawer's top position

src/lib/component/base/Drawer/MenuItem.tsx
Avoids using the active state for menu items that do not have a link.
=> avoid using active state for menu items without link

src/lib/component/partial/ExpandableKeyValueChip/ExpandableKeyValueChip.js, src/lib/component/partial/KeyValueChip/KeyValueChip.tsx
Ensures labels and annotations are clickable.
A regression introduced in #278 meant that the onClick handler was no longer being passed to the chip.
Manual
=> Ensures labels and annotations are clickable

src/lib/component/relocation/BannerWell.tsx, src/lib/component/relocation/ToastWell.tsx
Avoids settings the height of the well contents to `null`.
Can cause a `TypeError` if the browser window is resized or the toast/banner is unmounted.
Manual
=> Avoid null references in Well components

src/lib/component/partial/HandlersList/HandlersList.js, src/lib/component/view/HandlersView.tsx
Ensure that the currently selected filter is reflected in the preset filter dropdown.
Better communicate currently applied filter.
Manual
=> Ensure handlers view filters appear selected

src/lib/apollo/client.tsx, src/lib/apollo/resolvers/lastNamespace.graphql, src/lib/apollo/resolvers/lastNamespace.js
Allows last viewed cluster to be persisted in localStorage and retrieved through the GraphQL interface.
=> Allows last viewed cluster to be persisted

src/app/index.js, src/lib/component/base/Drawer/MenuItem.tsx, src/lib/component/icon/Missing.tsx, src/lib/component/icon/index.tsx, src/lib/component/partial/NotFound.js, src/lib/component/view/NamespaceNotFoundView.js
Re-adds the namespace switcher menu option to the 404 page. 
Without the menu item you would either need to know a valid namespace, navigate to the app root, or logout to continue.
Manual
=> Add namespace switcher to 404 page

src/lib/component/partial/Preferences.js
Truncate the list of groups displayed in the Preferences pane if the user has more than five. 
Closes #290 
Manual
=> Truncate list of groups if user has more than five

src/lib/component/partial/EventsList/EventsListItem.js
Disable resolve event button when status of the check is already zero.
Closes #46 
Manual
=> Disable resolve event button when already ok

src/lib/component/partial/EventDetailsContainer/EventDetailsEntitySummary.js
Unfortunately the last seen value is pulled from the event, so it is only relevant at the time the event was fired. As a result I've removed it to help avoid this confusion.
Closes #72
Manual
=> Remove last seen field from summary on events view

src/lib/component/partial/EventsList/EventsList.js, src/lib/component/toast/ManageResourceStatusToast.js, src/lib/component/toast/index.js
Display a toast when a user is unable to delete an event due to lack of permissions.
By virtue of the operation no longer leading to an exception, this helps relieve some of the pain from #110.
Manual
=> Display toast when user is unable to delete event

src/lib/component/partial/EntityDetailsContainer/EntityDetailsInformation.js
Fixes issue where the deregistration handler would not be displayed correctly on the entity details page. Additionally turned the label into a link so that user's can view the details of the handler.
Closes sensu/sensu-go#3021
Manual
=> Fix missing deregistration handler in entity page

src/lib/component/partial/SigninDialog/SigninForm.js
Trim whitespace from username when signing in.
Closes #303 
Manual.
=> Trim whitespace from username when signing in

src/lib/component/partial/CheckDetailsContainer/CheckDetailsExecuteAction.js, src/lib/component/partial/ChecksList/ChecksList.tsx, src/lib/component/partial/EventDetailsContainer/EventDetailsCheckSummary.js, src/lib/component/partial/EventDetailsContainer/EventDetailsHookSummary.tsx, src/lib/component/relocation/Relocation.js
Reflect check hook output on the event details view.
Closes #38 
Manual.
=> Reflect check hook output on the event details view

src/lib/component/base/KeyboardInput/KeyboardInput.tsx
Adds a high contrast theme
We want to make the web ui as accessible as possible.
=> [Web] High contrast theme

src/lib/component/banner/RepoMoveBanner.js, src/lib/component/banner/index.js, src/lib/component/partial/DeprecationAlert.js, src/lib/component/partial/GlobalAlert.js, src/lib/component/partial/index.js, src/lib/component/root/AppRoot.js
Closes [#1069](https://github.com/sensu/sensu-enterprise-go/issues/1069)
We want to inform people about changes coming to the web ui/repo
=> Adds a banner for upcoming changes

src/lib/util/authAPI.js, src/lib/util/base64.ts
Fixes issue where those with credentials that included non-ascii characters were unable to authenticate.
---
=> Properly base64 encode characters outside of the Latin1 range

INSTALL.md, scripts/serve.js
Adding a option through an environment variable (NODE_PROXY_SECURE) to set "secure: false" in the proxy config in the serve.js file. If the environment variable is not set it will default to "secure: true"
Current config requires a CA signed SSL certificate even in a development environment. 
Yes, I have updated the INSTALL.MD file. 
Deployed open source sensu web with my changes in my testing enviroment. The 500 error I was seeing no longer appeared after the change and I was allowed to connect to the sensu-backend service. 
https://github.com/sensu/web/issues/362
=> Added option in scripts/serve.js. Updated INSTALL.MD documentation
