sensu/web

- src/lib/apollo/client.js
- src/lib/apollo/resolvers/auth.js
Fixes a bug causing the app to crash after logging out and logging back in without refreshing the browser.
> Fix error caused by cache reset on logout

- src/lib/component/view/CheckDetailsView.js
- src/lib/component/view/EntityDetailsView.js
> Query details using given query param

- src/app/index.js
- src/lib/component/partial/Drawer.js
- src/lib/component/partial/QuickNav/Button.js
- src/lib/component/partial/QuickNav/Nav.js
- src/lib/component/util/NavigationProvider/NavigationProvider.js
- src/lib/component/util/NavigationProvider/WithNavigation.js
- src/lib/component/util/NavigationProvider/context.js
- src/lib/component/util/NavigationProvider/index.js
- src/lib/component/util/index.js
- src/vendor/react.js
NavigationProvider allows arbitrary components within the hierarchy to reference nav links declared in a single place at the app root.
> Create NavigationProvider component

- src/app/index.js
- src/lib/util/index.js
- src/lib/util/serviceWorker.js
> Add app initializer step to update service workers

- package.json
- yarn.lock
Both packages are used by devtooling vulnerabilities do not affect prod build.
> Update packages failing audit

- src/lib/component/partial/CheckDetailsContainer/CheckDetailsToolbar.js
- src/lib/component/partial/ChecksList/ChecksListHeader.js
- src/lib/component/partial/EntitiesList/EntitiesListHeader.js
- src/lib/component/partial/EntityDetailsContainer/EntityDetailsToolbar.js
- src/lib/component/partial/EventDetailsContainer/EventDetailsToolbar.js
- src/lib/component/partial/EventsList/EventsListHeader.js
- src/lib/component/partial/EventsList/EventsListItem.js
Closes sensu/sensu-enterprise-go#312.
> Emphasize delete button on all views

- src/vendor/react-spring.js
> Remove re-export of unexported keyword

- src/lib/component/partial/ToolbarMenu/Partitioner.js
> Use key to reference toolbar item instead of removed id prop

- .github/ISSUE_TEMPLATE/bug_template.md
- .github/ISSUE_TEMPLATE/feature_template.md
- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Should be the last PR, I had somehow missed a small bit of text in one of the several guides I looked at which mentioned name and about were required.
> Add required front matter for template

- .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
I still don't think the label application works, but it's really hard to find anything about it. I will continue trying, and unfortunately creating PRs because there's no good way to do this.
> remove frontmatter from PR template

- src/lib/component/partial/SigninDialog/SigninForm.js
Avoid exception when submitting empty SignIn form
Closes #32 
Yup
Nah.
Too the opportunity to refactor the component to use React hooks.
None required.
Manual.
> Avoid exception when submitting empty SignIn form

- package.json
- src/app/index.js
- src/lib/apollo/resolvers/deleted.graphql
- src/lib/apollo/stateLink.js
- src/lib/component/partial/CheckDetailsContainer/CheckDetailsConfiguration.js
- src/lib/component/partial/EntityDetailsContainer/EntityDetailsInformation.js
- src/lib/component/partial/HandlerDetailsContainer/HandlerDetailsConfiguration.js
- src/lib/component/partial/LabelsAnnotationsCell/LabelsAnnotationsCell.js
- src/lib/component/partial/MutatorDetailsContainer/MutatorDetailsConfiguration.tsx
- src/lib/component/partial/MutatorDetailsContainer/MutatorDetailsContainer.tsx
- src/lib/component/partial/MutatorDetailsContainer/MutatorDetailsToolbar.tsx
- src/lib/component/partial/MutatorDetailsContainer/index.tsx
- src/lib/component/partial/index.js
- src/lib/component/util/useRouter.tsx
- src/lib/component/view/MutatorDetailsView.tsx
- src/lib/component/view/index.js
- src/lib/util/filterParams.test.js
Adds new view for viewing mutator details.
Closes #148 
No.
Nope.
It's unlikely any changes will be required.
Manual.
> Adds new view for viewing mutator details

- src/app/index.js
- src/lib/component/icon/index.js
- src/lib/component/partial/MutatorsList/MutatorsList.js
- src/lib/component/partial/MutatorsList/MutatorsListHeader.js
- src/lib/component/partial/MutatorsList/MutatorsListItem.js
- src/lib/component/partial/MutatorsList/MutatorsListItemDetails.js
- src/lib/component/partial/MutatorsList/MutatorsListToolbar.js
- src/lib/component/partial/MutatorsList/index.js
- src/lib/component/partial/index.js
- src/lib/component/view/MutatorsView.js
- src/lib/component/view/index.js
Adds a list view for Mutators
We want to see all our lovely resources!
Yes, in sensu-go
Nah
Nah
Possibly, but will talk about it
Manually.
> Mutator list view

- src/lib/component/partial/ContextSwitcher/ContextSwitcherList.tsx
- src/lib/component/view/EventFilterDetailsView.tsx
Without the layout the user is unable to easily navigate away.
> Updates event filters not found view to include app layout

- src/lib/apollo/resolvers/auth.js
- src/lib/component/base/AppLayout/AppLayout.js
- src/lib/component/partial/AppLayout.js
Allow pages to optionally disable breadcrumbs.
Manual.
> Optionally allow for breadcrumbs to be disabled

- src/lib/component/partial/CheckDetailsContainer/CheckDetailsConfiguration.js
- src/lib/component/partial/EntityDetailsContainer/EntityDetailsInformation.js
- src/lib/component/partial/EventDetailsContainer/EventDetailsCheckSummary.js
- src/lib/component/partial/EventDetailsContainer/EventDetailsEntitySummary.js
- src/lib/component/partial/EventFilterDetailsContainer/EventFilterDetailsConfiguration.tsx
- src/lib/component/partial/HandlerDetailsContainer/HandlerDetailsConfiguration.js
- src/lib/component/partial/LabelsAnnotationsCell/LabelsAnnotationsCell.js
- src/lib/component/partial/MutatorDetailsContainer/MutatorDetailsConfiguration.tsx
Closes #[3196](https://github.com/sensu/sensu-go/issues/3196) 
Adds labels and annotations to the event details page
Requested
> Adds check and entity labels to the event details view

- src/lib/apollo/httpLink.tsx
- src/lib/component/util/AuthInvalidRoute.js
- src/lib/component/util/NamespaceRoute.js
- src/lib/component/view/CheckDetailsView.tsx
- src/lib/component/view/ChecksView.tsx
- src/lib/component/view/EntitiesView.tsx
- src/lib/component/view/EntityDetailsView.tsx
- src/lib/component/view/EventDetailsView.tsx
- src/lib/component/view/EventFilterDetailsView.tsx
- src/lib/component/view/EventFiltersView.tsx
- src/lib/component/view/EventsView.tsx
- src/lib/component/view/HandlerDetailsView.tsx
- src/lib/component/view/HandlersView.tsx
- src/lib/component/view/MutatorDetailsView.tsx
- src/lib/component/view/MutatorsView.tsx
- src/lib/component/view/SilencesView.tsx
- src/lib/util/fetchError.tsx
- src/lib/util/index.tsx
With the exception of 500 (Internal Err) & 501 (Not Implemented), set the
offline status to true if a server error is encountered.
> Set offline status when non-500 server errs occur

- src/lib/component/partial/CheckTimeline/CheckTimeline.tsx
Omits duplicate entries in event timeline.
Closes #231
> [Web] Omit duplicate entries in event timeline

- src/lib/component/partial/Annotation/Annotation.js
- src/lib/component/partial/Annotation/index.js
- src/lib/component/partial/Label/Label.js
- src/lib/component/partial/LabelsAnnotationsCell/LabelsAnnotationsCell.js
- src/lib/component/util/index.tsx
- src/lib/component/util/parseLink.js
Closes #246 
Adds link parsing to annotations.
> Add link parsing to annotations

- src/lib/component/partial/Annotation/Annotation.js
A bad import somehow snuck past CI and testing, this fixes it.
> Fix an import for CodeBlocks

- src/lib/component/base/Drawer/MenuItem.tsx
- yarn.lock
---
Increases visibility of which page(s) the user is currently on.
> Adds an active state to drawer items

- src/app/index.js
- src/lib/component/util/ConfigurationProvider/ConfigurationProvider.tsx
- src/lib/component/util/ConfigurationProvider/context.tsx
- src/lib/component/util/ConfigurationProvider/index.tsx
- src/lib/component/util/ConfigurationProvider/useConfigurationProvider.tsx
- src/lib/component/util/index.tsx
Related to #223 
Adds a ConfigurationProvider to allow the setting of particular defaults in the web ui
> Add ConfigurationProvider

- src/app/index.js
- src/lib/apollo/resolvers/theme.js
- src/lib/component/base/AppThemeProvider.tsx
- src/lib/component/partial/Preferences.js
- src/lib/component/util/ConfigurationProvider/context.tsx
- src/lib/component/util/index.tsx
- src/lib/component/util/usePreferredTheme.tsx
- src/lib/component/view/ChecksView.tsx
- src/lib/component/view/EntitiesView.tsx
- src/lib/component/view/EventFiltersView.tsx
- src/lib/component/view/EventsView.tsx
- src/lib/component/view/HandlersView.tsx
- src/lib/component/view/MutatorsView.tsx
- src/lib/component/view/SilencesView.tsx
- src/lib/constant/configuration.tsx
- src/lib/constant/index.tsx
Adds a global configurable page size and theme preference.
> Adds global configurable page size and theme preference

- src/lib/component/base/ThemeProvider.js
- src/lib/constant/configuration.tsx
Could lead to exception when the configured default was not found.
> Fix issue where default theme was misconfigured

- src/lib/theme/defaults.js
> Increase font-weight for headers

- package.json
- src/lib/component/base/RelativeDate/RelativeToCurrentDate.tsx
- src/lib/component/partial/EntityDetailsContainer/EntityDetailsContainer.js
- src/lib/component/partial/EntityDetailsContainer/EntityDetailsInformation.js
- src/lib/component/partial/EntityDetailsContainer/EntityDetailsProcesses.tsx
- src/lib/theme/defaults.js
Reflect new platform & local service info on entity page.
Requires sensu/sensu-go#3732
Closes sensu/sensu-enterprise-go#957
Manual
> Reflect platform & local service info on entity page

- src/lib/component/base/Drawer/Drawer.tsx
- src/lib/component/base/Drawer/MenuItem.tsx
- src/lib/component/base/SearchBox/SearchBox.tsx
- src/lib/component/partial/ChecksList/ChecksListItem.js
- src/lib/component/partial/ContextSwitcher/ContextSwitcher.tsx
- src/lib/component/partial/EntitiesList/EntitiesListItem.js
- src/lib/component/partial/EventsList/EventsListItem.js
- src/lib/component/partial/ListHeader/ListHeader.js
- src/lib/component/partial/ListSortSelector/ListSortSelector.js
- src/lib/component/partial/Preferences.js
- src/lib/component/partial/SigninDialog/SigninForm.js
- src/lib/component/partial/SilenceEntryDialog.js
- src/lib/component/partial/SilenceEntryForm/SilenceEntryFormCheckPanel.js
- src/lib/component/partial/SilenceEntryForm/SilenceEntryFormReasonPanel.js
- src/lib/component/partial/SilenceEntryForm/SilenceEntryFormSubscriptionPanel.js
- src/lib/component/partial/SilencesList/SilencesListItem.js
Ensure all form elements are properly labelled.
Helps with screen readers and other accessibility tooling.
Storybook's a11y plugin & [Accessibility Insights for Web](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni?hl=en).
> Ensure form elements are properly labelled

- src/lib/component/partial/EntityDetailsContainer/EntityDetailsInformation.js
- src/lib/component/partial/EntityDetailsContainer/EntityDetailsProcesses.tsx
- yarn.lock
- No longer display float type, ~~it doesn't appear as if the backend is even setting it at the moment.~~ The value is being set but only applies to the mips arch. https://github.com/sensu/sensu-go/blob/2c72baa0beee6b1509dab14ebbc7ca3c1d56b5da/system/system.go#L48
- Properly reference the libc implementation used.
- No longer capitalize the process names.
Closes #308 
Manual.
> Tweaks for entity details view

- src/lib/component/base/CodeBlock/CodeBlock.js
- src/lib/component/base/Drawer/Drawer.tsx
- src/lib/component/base/Drawer/MenuItem.tsx
- src/lib/component/partial/KeyValueChip/KeyValueChip.tsx
- src/lib/component/partial/Preferences.js
- src/lib/component/partial/SilencesList/SilencesListItem.js
- src/lib/theme/defaults.js
- src/lib/theme/highcontrast.js
- src/lib/theme/index.js
Adds a high contrast theme
We want to make the web ui as accessible as possible.
> [Web] High contrast theme

- src/lib/component/partial/ContextSwitcher/ContextSwitcherList.tsx
- src/lib/component/partial/EventsList/EventsListHeader.js
- src/lib/component/partial/ExpandableKeyValueChip/ExpandableKeyValueChip.js
Pulls in relevant bug fixes from upstream project.
* Labels with a value of `0` or `false` are now properly rendered.
* Avoids potential out of bounds exception when selecting a changing with keyboard bindings.
* Ensures that sort order on events list can be changed after a value was previously selected.
> Pull relevant bugfixes from upstream project

- INSTALL.md
- README.md
- scripts/serve.js
Some more detailed installation and running instructions, and a modest change to code for better running in production.
I did an installation on a Sensu server, and as I had to google some of the steps, I figured it's best if I write them down to save other people the same hassle. Also, I prefer to run things behind an Nginx proxy, so want it running on `localhost` rather than all interfaces (as is the default).
Issue to compliment this PR: https://github.com/sensu/web/issues/338
It's a pretty tiny code change which won't change behaviour unless you want it to. The main contrib here is documentation.
No.
No.
Yes.
I only performed manual tests on this change.
> Installation Instructions and Prod-Friendly Running

- package.json
- scripts/serve.js
- src/lib/component/partial/ContextSwitcher/ContextSwitcher.tsx
- yarn.lock
Bump `http-proxy` dependency to address [GHSA-6x33-pw7p-hmpq](https://github.com/advisories/GHSA-6x33-pw7p-hmpq).
> Bump http-proxy dependency

- src/lib/component/partial/EventDetailsContainer/EventDetailsCheckSummary.js
Signed-off-by: Luc Dandoy <luc.dandoy@gmail.com>
In event details, for fields `Issued at` & `Ran at`, seconds are now displayed
This will fix #353 .
Since it's possible to schedule check to be executed every X seconds, I thinks it's nice to know when the check is executed exactly.
Not sure, since it's a very little cosmetic change.
I'm unsure if this behaviour can be "fixed" for everyone or if it's needed to control this through per user parameters (in such case I think it will be more difficult to achieve :) )
Nope
I dont think documentation update is needed.
Test performed on various WebBrowser on MacOS (Chrome/Safari/Firefox), Linux (Firefox), and iOS (Safari/Firefox)
> Displaying seconds in event details for "Ran at" and "Issued at" fields

- babel.config.js
- package.json
- src/lib/component/base/AutoSuggest.tsx
- src/lib/component/partial/AutosuggestSelectMenu.tsx
- src/lib/component/partial/ChecksList/ChecksListHeader.js
- src/lib/component/partial/EntitiesList/EntitiesListHeader.js
- src/lib/component/partial/EventsList/EventsListHeader.js
- src/lib/component/partial/SilencesList/SilencesListHeader.js
- src/lib/component/util/useAutosuggest.tsx
- src/lib/util/array.ts
- tsconfig.json
- yarn.lock
> Remove references to deprectated subscription field

- README.md
Because it refers to a plural sentence, contributions should be used instead of contribution.
> Grammatical Mistake

- README.md
> Update README w/ roadmap
